# Generated by Django 6.0.4 on 2026-05-16 23:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('tempo_estimado', models.IntegerField(help_text='Minutos para atendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao_arterial', models.CharField(max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(45.0)])),
                ('frequencia_cardiaca', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendimentos.paciente')),
                ('prioridade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimentos.prioridade')),
            ],
            options={
                'verbose_name_plural': 'Triagens',
                'ordering': ['-data_hora'],
            },
        ),
    ]
