# Generated by Django 6.0.4 on 2026-05-27 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='cpf',
            new_name='cpf_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nome',
            new_name='nome_paciente',
        ),
        migrations.RenameField(
            model_name='prioridade',
            old_name='nome',
            new_name='nome_prioridade',
        ),
    ]
