# Generated by Django 6.0.4 on 2026-05-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('E', 'Enfermeiro'), ('T', 'Tecnico de Enfermagem'), ('A', 'Administrador')], default='E', max_length=1),
        ),
    ]
