# Generated by Django 6.0.4 on 2026-05-27 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='cpf',
            new_name='cpf_profissional',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo',
            new_name='tipo_profissional',
        ),
    ]
