# Generated by Django 6.0.4 on 2026-05-27 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_cpf_usuario_cpf_profissional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_profissional',
            new_name='tipo',
        ),
    ]
